# Generated by Django 4.2.1 on 2023-06-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnsTruCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Код ЕНС ТРУ")),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Документ лота",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(blank=True, null=True, verbose_name="Номер"),
                ),
                (
                    "register_number",
                    models.CharField(
                        blank=True, null=True, verbose_name="Регистрационный номер"
                    ),
                ),
                ("type", models.CharField(blank=True, null=True, verbose_name="Тип")),
                (
                    "trade_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="Торговое наименование"
                    ),
                ),
                ("view", models.CharField(blank=True, null=True, verbose_name="Вид")),
                ("register_date", models.DateField(blank=True, null=True)),
                (
                    "time",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Срок"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата истечения"
                    ),
                ),
                (
                    "producer",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Страна"
                    ),
                ),
                ("classification", models.CharField(blank=True, null=True)),
                (
                    "IGN",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="МНН"
                    ),
                ),
                (
                    "atx_classification",
                    models.CharField(
                        blank=True, null=True, verbose_name="ATX классификация"
                    ),
                ),
                (
                    "med_form",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Лек. форма",
                    ),
                ),
                (
                    "release_form",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Форма выпуска",
                    ),
                ),
                (
                    "shelf_life",
                    models.CharField(
                        blank=True, null=True, verbose_name="Срок хранения"
                    ),
                ),
                ("GMP", models.CharField(blank=True, null=True, verbose_name="GMP")),
                (
                    "generic",
                    models.CharField(blank=True, null=True, verbose_name="Генерик"),
                ),
                (
                    "recipe",
                    models.CharField(blank=True, null=True, verbose_name="Рецепт"),
                ),
                (
                    "trademark",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Торговая марка"
                    ),
                ),
                (
                    "patent",
                    models.CharField(blank=True, null=True, verbose_name="Патент"),
                ),
                (
                    "nd_type",
                    models.CharField(blank=True, null=True, verbose_name="Тип НД"),
                ),
                (
                    "nd_number",
                    models.CharField(blank=True, null=True, verbose_name="Номер НД"),
                ),
                (
                    "dosage_and_concentration",
                    models.CharField(
                        blank=True, null=True, verbose_name="Дозировка и концентрация"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefTradeMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Вид закупа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(blank=True, null=True, verbose_name="Поставщик"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, null=True, verbose_name="Телефонный номер"
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, null=True, verbose_name="email"),
                ),
                (
                    "product_name",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Торговое наименование поставляемого товара",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="tender", name="additional_info",),
        migrations.RemoveField(model_name="tender", name="company",),
        migrations.RemoveField(model_name="tender", name="date",),
        migrations.RemoveField(model_name="tender", name="deadline",),
        migrations.RemoveField(model_name="tender", name="delivery_deadline",),
        migrations.RemoveField(model_name="tender", name="measure_unit",),
        migrations.RemoveField(model_name="tender", name="name",),
        migrations.RemoveField(model_name="tender", name="planned_amount",),
        migrations.RemoveField(model_name="tender", name="price_per_unit",),
        migrations.RemoveField(model_name="tender", name="procurement_type",),
        migrations.RemoveField(model_name="tender", name="proposed_product_name",),
        migrations.RemoveField(model_name="tender", name="quantity",),
        migrations.RemoveField(model_name="tender", name="supplier",),
        migrations.AlterField(
            model_name="tender",
            name="bidding_price_per_unit",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Цена подачи (за единицу)",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="budget_price_per_unit",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Цена бюджета (за единицу)",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="delivery_rate",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Коэффициент доставки",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="lot_link",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ссылка на электронный лот"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="overall_contract_amount",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Общая сумма договора",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="overall_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Общая информация"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="overall_profit",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Общая прибыль с проекта",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="overall_purchase_amount",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Общая сумма закупа"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="paper_ad_link",
            field=models.TextField(
                blank=True, null=True, verbose_name="№/ссылка на бумажное объявление"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="profit_rate",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Коэффициент прибыли",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="purchase_price",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Цена закупа"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="purchase_price_per_unit",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Цена закупа (за единицу)",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="supplier_discount",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Скидка от поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="vat",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="НДС"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="winning_price",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Выигрышная цена"
            ),
        ),
        migrations.CreateModel(
            name="TrdBuy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publish_date",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Крайний срок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                (
                    "ref_trade_methods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarttender.reftrademethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Цена за единицу",
                    ),
                ),
                (
                    "count",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Количество"
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Плановая сумма",
                    ),
                ),
                (
                    "supply_date_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Срок поставки"
                    ),
                ),
                (
                    "ref_enstru_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Код ЕНС ТРУ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                (
                    "ref_units",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarttender.refunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="№ лота"
                    ),
                ),
                (
                    "customer_name_ru",
                    models.TextField(blank=True, null=True, verbose_name="Учреждение"),
                ),
                (
                    "name_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                (
                    "files",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarttender.file",
                    ),
                ),
                (
                    "plans",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarttender.plan",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarttender.product",
                    ),
                ),
                (
                    "suppliers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarttender.supplier",
                    ),
                ),
                (
                    "trd_buy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarttender.trdbuy",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="tender",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.lot",
            ),
        ),
    ]
