# Generated by Django 4.2.1 on 2023-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttender', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GMP',
            field=models.CharField(verbose_name='GMP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic',
            field=models.CharField(verbose_name='Генерик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nd_number',
            field=models.CharField(blank=True, null=True, verbose_name='Номер НД'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nd_type',
            field=models.CharField(blank=True, null=True, verbose_name='Тип НД'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='patent',
            field=models.CharField(verbose_name='Патент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe',
            field=models.CharField(verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='register_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
