# Generated by Django 4.2.1 on 2023-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttender', '0002_enstrucode_file_product_reftrademethod_refunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(blank=True, null=True, verbose_name='Торговое наименование')),
                ('mnn', models.CharField(blank=True, null=True, verbose_name='МНН')),
                ('medicine', models.CharField(blank=True, null=True, verbose_name='Лекарственная форма')),
                ('atx_code', models.CharField(blank=True, null=True, verbose_name='АТХ код')),
                ('registration_number', models.CharField(blank=True, null=True, verbose_name='Регистрационное удостоверение')),
                ('unit', models.CharField(blank=True, null=True, verbose_name='Единица измерения')),
                ('limit_price', models.CharField(blank=True, null=True, verbose_name='Предельная цена')),
            ],
        ),
    ]
