# Generated by Django 4.2.1 on 2023-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttender', '0003_alter_product_gmp_alter_product_generic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок'),
        ),
    ]
