# Generated by Django 4.2.1 on 2023-06-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttender', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='number',
            field=models.CharField(blank=True, null=True, verbose_name='Торговое наименование'),
        ),
    ]
