# Generated by Django 4.2.1 on 2023-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0003_rename_ign_product_ign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enstrucode",
            name="name",
            field=models.TextField(verbose_name="Наименование"),
        ),
    ]
