# Generated by Django 4.2.1 on 2023-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttender', '0004_alter_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='med_form',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Лек. форма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(max_length=1000, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_form',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Форма выпуска'),
        ),
    ]
