# Generated by Django 4.2.1 on 2023-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0004_alter_enstrucode_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enstrucode",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="Наименование"),
        ),
    ]
