# Generated by Django 4.2.1 on 2023-06-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0005_alter_enstrucode_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_discount",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Скидка от поставщика",
                    ),
                ),
                (
                    "vat",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="НДС"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Менеджер"
                    ),
                ),
                (
                    "purchase_price",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Цена закупа",
                    ),
                ),
                (
                    "overall_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Общая информация"
                    ),
                ),
                (
                    "paper_ad_link",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="№/ссылка на бумажное объявление",
                    ),
                ),
                (
                    "lot_link",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ссылка на электронный лот"
                    ),
                ),
                (
                    "profit_rate",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Коэффициент прибыли",
                    ),
                ),
                (
                    "delivery_rate",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Коэффициент доставки",
                    ),
                ),
                (
                    "purchase_price_per_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Цена закупа (за единицу)",
                    ),
                ),
                (
                    "bidding_price_per_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Цена подачи (за единицу)",
                    ),
                ),
                (
                    "budget_price_per_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Цена бюджета (за единицу)",
                    ),
                ),
                (
                    "overall_profit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Общая прибыль с проекта",
                    ),
                ),
                (
                    "overall_purchase_amount",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Общая сумма закупа",
                    ),
                ),
                (
                    "overall_contract_amount",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Общая сумма договора",
                    ),
                ),
                (
                    "winning_price",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Выигрышная цена",
                    ),
                ),
                (
                    "commercial_offer_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст для КП"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefBuyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_kz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Статус объявления на государственном языке",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Статус объявления на русском языке",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Код статуса объявления",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefSubjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_kz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Предмет закупки на государственном языке",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Предмет закупки на русском языке",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefTypeTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_kz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тип закупки на государственном языке",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тип закупки на русском языке",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="lot", name="files",),
        migrations.RemoveField(model_name="lot", name="plans",),
        migrations.AddField(
            model_name="enstrucode",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="enstrucode",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="file",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="smarttender.lot",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="name_kz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование документа на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="name_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование документа на русском языке",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="original_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Оригинальное имя файла",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="amount",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Общая сумма"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="count",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Общее количество"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="customer_name_kz",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Наименование заказчика на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="description_kz",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Детальное описание на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="dumping",
            field=models.BooleanField(default=False, verbose_name="Признак демпинга"),
        ),
        migrations.AddField(
            model_name="lot",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="lot",
            name="name_kz",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Наименование на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="desc_kz",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Краткая характеристика на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="desc_ru",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Краткая характеристика на русском языке",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="plan",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="smarttender.lot",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_kz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование на русском языке",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="subject_name_kz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование заказчика на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="subject_name_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование заказчика на русском языке",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="reftrademethod",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Цифровой код"
            ),
        ),
        migrations.AddField(
            model_name="reftrademethod",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="reftrademethod",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="reftrademethod",
            name="name_kz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Способ закупки на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="reftrademethod",
            name="symbolCode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Символьный код"
            ),
        ),
        migrations.AddField(
            model_name="refunit",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="refunit",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="refunit",
            name="name_kz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Единица измерения на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="count_lots",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Количество лотов в объявлении"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="customer_name_kz",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Наименование заказчика на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="customer_name_ru",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Наименование заказчика на русском языке",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="fin_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Финансовый год"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="itogi_date_public",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата публикации итогов"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="name_kz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="name_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование на русском языке",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="number_anno",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Номер объявления"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="org_bin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="БИН Организатора"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="org_name_kz",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование организатора на государственном языке",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="org_name_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование организатора на русском языке",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="org_pid",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ИД Организатора"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата начала приема заявок"
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="total_sum",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Общая сумма запланированная для закупки (Сумма закупки)",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Путь до файла"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="customer_name_ru",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Наименование заказчика на русском языке",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="description_ru",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Детальное описание на русском языке",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="lot_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Номер лота"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="name_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Наименование на русском языке"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="trd_buy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="smarttender.trdbuy",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="amount",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Общая сумма, утвержденная для закупки",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="count",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Количество / объем"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="ref_enstru_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Код КТРУ (ЕНС ТРУ)"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="ref_units",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="smarttender.refunit",
            ),
        ),
        migrations.AlterField(
            model_name="reftrademethod",
            name="name_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Способ закупки на русском языке",
            ),
        ),
        migrations.AlterField(
            model_name="refunit",
            name="name_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Единица измерения на русском языке",
            ),
        ),
        migrations.AlterField(
            model_name="trdbuy",
            name="end_date",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Дата окончания приема заявок",
            ),
        ),
        migrations.AlterField(
            model_name="trdbuy",
            name="publish_date",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Дата и время публикации",
            ),
        ),
        migrations.AlterField(
            model_name="trdbuy",
            name="ref_trade_methods",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.reftrademethod",
            ),
        ),
        migrations.DeleteModel(name="Tender",),
        migrations.AddField(
            model_name="trdbuy",
            name="calculation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.calculation",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="ref_buy_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.refbuystatus",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="ref_subject_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.refsubjecttype",
            ),
        ),
        migrations.AddField(
            model_name="trdbuy",
            name="ref_type_trade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.reftypetrade",
            ),
        ),
    ]
