# Generated by Django 4.2.1 on 2023-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttender', '0005_alter_product_med_form_alter_product_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='tender',
            name='price_without_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена без скидки'),
        ),
    ]
