# Generated by Django 4.2.1 on 2023-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "smarttender",
            "0006_calculation_refbuystatus_refsubjecttype_reftypetrade_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="lot", name="products",),
        migrations.RemoveField(model_name="lot", name="suppliers",),
        migrations.AddField(
            model_name="lot",
            name="products",
            field=models.ManyToManyField(
                blank=True, null=True, to="smarttender.product"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True, null=True, to="smarttender.supplier"
            ),
        ),
    ]
