# Generated by Django 4.2.1 on 2023-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0006_tender_price_with_discount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot", models.CharField(max_length=255, verbose_name="№ лота")),
                ("company", models.TextField(verbose_name="Учреждение")),
                ("name", models.TextField(verbose_name="Наименование")),
            ],
        ),
    ]
