# Generated by Django 4.2.1 on 2023-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0007_tenderapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderapi",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Крайний срок"),
        ),
    ]
