# Generated by Django 4.2.1 on 2023-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0007_remove_lot_products_remove_lot_suppliers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="products",
            field=models.ManyToManyField(blank=True, to="smarttender.product"),
        ),
        migrations.AlterField(
            model_name="lot",
            name="suppliers",
            field=models.ManyToManyField(blank=True, to="smarttender.supplier"),
        ),
    ]
