# Generated by Django 4.2.1 on 2023-06-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0008_alter_lot_products_alter_lot_suppliers"),
    ]

    operations = [
        migrations.RemoveField(model_name="trdbuy", name="calculation",),
        migrations.AddField(
            model_name="calculation",
            name="trd_buy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.trdbuy",
            ),
        ),
    ]
