# Generated by Django 4.2.1 on 2023-05-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0008_tenderapi_deadline"),
    ]

    operations = [
        migrations.RemoveField(model_name="tenderapi", name="deadline",),
    ]
