# Generated by Django 4.2.1 on 2023-06-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0009_remove_trdbuy_calculation_calculation_trd_buy"),
    ]

    operations = [
        migrations.RemoveField(model_name="plan", name="ref_units",),
        migrations.AlterField(
            model_name="trdbuy",
            name="ref_buy_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trd_buys",
                to="smarttender.refbuystatus",
            ),
        ),
        migrations.AlterField(
            model_name="trdbuy",
            name="ref_subject_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trd_buys",
                to="smarttender.refsubjecttype",
            ),
        ),
        migrations.AlterField(
            model_name="trdbuy",
            name="ref_trade_methods",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trd_buys",
                to="smarttender.reftrademethod",
            ),
        ),
        migrations.AlterField(
            model_name="trdbuy",
            name="ref_type_trade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trd_buys",
                to="smarttender.reftypetrade",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="ref_units",
            field=models.ManyToManyField(blank=True, to="smarttender.refunit"),
        ),
    ]
