# Generated by Django 4.2.1 on 2023-06-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "smarttender",
            "0010_remove_plan_ref_units_alter_trdbuy_ref_buy_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="calculation", name="trd_buy",),
        migrations.AddField(
            model_name="calculation",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.lot",
            ),
        ),
    ]
