# Generated by Django 4.2.1 on 2023-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0012_remove_lot_products_remove_lot_suppliers_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trdbuy",
            name="itogi_date_public",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Дата публикации итогов",
            ),
        ),
        migrations.AlterField(
            model_name="trdbuy",
            name="start_date",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Дата начала приема заявок",
            ),
        ),
    ]
