# Generated by Django 4.2.1 on 2023-06-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0013_alter_trdbuy_itogi_date_public_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reftrademethod", old_name="symbolCode", new_name="symbol_code",
        ),
    ]
