# Generated by Django 4.2.1 on 2023-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0014_rename_symbolcode_reftrademethod_symbol_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="trdbuy", name="ref_trade_methods",),
        migrations.AddField(
            model_name="trdbuy",
            name="ref_trade_methods",
            field=models.ManyToManyField(blank=True, to="smarttender.reftrademethod"),
        ),
    ]
