# Generated by Django 4.2.1 on 2023-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0017_remove_trdbuy_ref_buy_status_trdbuy_ref_buy_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="trdbuy", name="ref_type_trade",),
        migrations.AddField(
            model_name="trdbuy",
            name="ref_type_trade",
            field=models.ManyToManyField(blank=True, to="smarttender.reftypetrade"),
        ),
    ]
