# Generated by Django 4.2.1 on 2023-06-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0018_remove_trdbuy_ref_type_trade_trdbuy_ref_type_trade"),
    ]

    operations = [
        migrations.RemoveField(model_name="calculation", name="lot",),
        migrations.AddField(
            model_name="lot",
            name="calculation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="smarttender.calculation",
            ),
        ),
    ]
