# Generated by Django 4.2.1 on 2023-06-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0019_remove_calculation_lot_lot_calculation"),
    ]

    operations = [
        migrations.RemoveField(model_name="lot", name="calculation",),
        migrations.AddField(
            model_name="calculation",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarttender.lot",
            ),
        ),
    ]
