# Generated by Django 4.2.1 on 2023-07-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smarttender", "0006_optprice_remove_price_atx_code_and_more"),
        ("smarttender", "0021_alter_calculation_lot"),
    ]

    operations = []
